export const storageKey = 'arcade-tier-calculator-history'
export const adminStorageKey = 'arcade-admin-session'
export const officialResourcesStorageKey = 'arcade-official-resources'
export const languageStorageKey = 'arcade-language'
export const leaderboardStorageKey = 'arcade-leaderboard'
